import { contextBridge, ipcRenderer } from 'electron'
import { IPC } from '../shared/ipc'
import type { MuesliBridge } from '../shared/ipc'
import type { UploadProgress } from '../main/uploadMachine'

const bridge: MuesliBridge = {
  getConfig: () => ipcRenderer.invoke(IPC.getConfig),
  connect: (req) => ipcRenderer.invoke(IPC.connect, req),
  disconnect: () => ipcRenderer.invoke(IPC.disconnect),
  listNotes: (folderId?: string) => ipcRenderer.invoke(IPC.listNotes, folderId),
  listPeople: () => ipcRenderer.invoke(IPC.listPeople),
  listCompanies: () => ipcRenderer.invoke(IPC.listCompanies),
  listNoteActionItems: (noteId) => ipcRenderer.invoke(IPC.listNoteActionItems, noteId),
  getPerson: (id) => ipcRenderer.invoke(IPC.getPerson, id),
  getPersonNotes: (id) => ipcRenderer.invoke(IPC.getPersonNotes, id),
  updatePerson: (id, req) => ipcRenderer.invoke(IPC.updatePerson, id, req),
  updateActionItem: (id, req) => ipcRenderer.invoke(IPC.updateActionItem, id, req),
  mergePeople: (fromId, intoId) => ipcRenderer.invoke(IPC.mergePeople, fromId, intoId),
  deletePerson: (id) => ipcRenderer.invoke(IPC.deletePerson, id),
  getCompany: (id) => ipcRenderer.invoke(IPC.getCompany, id),
  getFull: (id) => ipcRenderer.invoke(IPC.getFull, id),
  createNote: (title) => ipcRenderer.invoke(IPC.createNote, title),
  updateBody: (id, content) => ipcRenderer.invoke(IPC.updateBody, id, content),
  updateTitle: (id, title) => ipcRenderer.invoke(IPC.updateTitle, id, title),
  deleteNote: (id) => ipcRenderer.invoke(IPC.deleteNote, id),
  duplicateNote: (id) => ipcRenderer.invoke(IPC.duplicateNote, id),
  pinNote: (id) => ipcRenderer.invoke(IPC.pinNote, id),
  unpinNote: (id) => ipcRenderer.invoke(IPC.unpinNote, id),
  linkNoteEvent: (id, eventId) => ipcRenderer.invoke(IPC.linkNoteEvent, id, eventId),
  unlinkNoteEvent: (id) => ipcRenderer.invoke(IPC.unlinkNoteEvent, id),
  listTrash: () => ipcRenderer.invoke(IPC.listTrash),
  restoreNote: (id) => ipcRenderer.invoke(IPC.restoreNote, id),
  retranscribeNote: (id, options) => ipcRenderer.invoke(IPC.retranscribeNote, id, options),
  permanentDeleteNote: (id) => ipcRenderer.invoke(IPC.permanentDeleteNote, id),
  getNoteAudioUrl: (noteId) => ipcRenderer.invoke(IPC.getNoteAudioUrl, noteId),
  uploadAudio: (req) => ipcRenderer.invoke(IPC.uploadAudio, req),
  startNoteStream: (noteId) => ipcRenderer.invoke(IPC.startNoteStream, noteId),
  stopNoteStream: (noteId) => ipcRenderer.invoke(IPC.stopNoteStream, noteId),
  sendNoteStreamAudio: (noteId, audio) => ipcRenderer.invoke(IPC.sendNoteStreamAudio, noteId, audio),
  addTag: (noteId, name) => ipcRenderer.invoke(IPC.addTag, noteId, name),
  removeTag: (noteId, name) => ipcRenderer.invoke(IPC.removeTag, noteId, name),
  renameTag: (id, name) => ipcRenderer.invoke(IPC.renameTag, id, name),
  deleteTag: (id) => ipcRenderer.invoke(IPC.deleteTag, id),
  listTags: () => ipcRenderer.invoke(IPC.listTags),
  listSmartLists: () => ipcRenderer.invoke(IPC.listSmartLists),
  createSmartList: (name, rule) => ipcRenderer.invoke(IPC.createSmartList, name, rule),
  updateSmartList: (id, name, rule) => ipcRenderer.invoke(IPC.updateSmartList, id, name, rule),
  deleteSmartList: (id) => ipcRenderer.invoke(IPC.deleteSmartList, id),
  listTrashedSmartLists: () => ipcRenderer.invoke(IPC.listTrashedSmartLists),
  restoreSmartList: (id) => ipcRenderer.invoke(IPC.restoreSmartList, id),
  permanentDeleteSmartList: (id) => ipcRenderer.invoke(IPC.permanentDeleteSmartList, id),
  listFolders: () => ipcRenderer.invoke(IPC.listFolders),
  createFolder: (name, parentId) => ipcRenderer.invoke(IPC.createFolder, name, parentId),
  updateFolder: (id, name, parentId) => ipcRenderer.invoke(IPC.updateFolder, id, name, parentId),
  deleteFolder: (id) => ipcRenderer.invoke(IPC.deleteFolder, id),
  reorderFolder: (id, afterId) => ipcRenderer.invoke(IPC.reorderFolder, id, afterId),
  reorderNoteInFolder: (folderId, noteId, afterId) => ipcRenderer.invoke(IPC.reorderNoteInFolder, folderId, noteId, afterId),
  listTrashedFolders: () => ipcRenderer.invoke(IPC.listTrashedFolders),
  restoreFolder: (id) => ipcRenderer.invoke(IPC.restoreFolder, id),
  permanentDeleteFolder: (id) => ipcRenderer.invoke(IPC.permanentDeleteFolder, id),
  addNoteFolder: (noteId, folderId) => ipcRenderer.invoke(IPC.addNoteFolder, noteId, folderId),
  removeNoteFolder: (noteId, folderId) => ipcRenderer.invoke(IPC.removeNoteFolder, noteId, folderId),
  listTemplates: () => ipcRenderer.invoke(IPC.listTemplates),
  createTemplate: (name, sections) => ipcRenderer.invoke(IPC.createTemplate, name, sections),
  updateTemplate: (id, name, sections) => ipcRenderer.invoke(IPC.updateTemplate, id, name, sections),
  deleteTemplate: (id) => ipcRenderer.invoke(IPC.deleteTemplate, id),
  exportFile: (defaultName, content) => ipcRenderer.invoke(IPC.exportFile, defaultName, content),
  exportNote: (noteId, format) => ipcRenderer.invoke(IPC.exportNote, noteId, format),
  exportAllNotes: () => ipcRenderer.invoke(IPC.exportAllNotes),
  retryNote: (id) => ipcRenderer.invoke(IPC.retryNote, id),
  processNextNote: (id) => ipcRenderer.invoke(IPC.processNextNote, id),
  resummarize: (id) => ipcRenderer.invoke(IPC.resummarize, id),
  regenerateSummary: (noteId, templateId) => ipcRenderer.invoke(IPC.regenerateSummary, noteId, templateId),
  search: (q, opts) => ipcRenderer.invoke(IPC.search, q, opts),
  getDefaultTranscriberStatus: () => ipcRenderer.invoke(IPC.getDefaultTranscriberStatus),
  checkAudioDedup: (audio: ArrayBuffer) => ipcRenderer.invoke(IPC.checkAudioDedup, audio),
  listSpeakerAliases: (noteId) => ipcRenderer.invoke(IPC.listSpeakerAliases, noteId),
  upsertSpeakerAlias: (noteId, label, aliasName) => ipcRenderer.invoke(IPC.upsertSpeakerAlias, noteId, label, aliasName),
  getDiarizationReview: (noteId) => ipcRenderer.invoke(IPC.getDiarizationReview, noteId),
  postDiarizationReview: (noteId, body) => ipcRenderer.invoke(IPC.postDiarizationReview, noteId, body),
  listConversations: (noteId) => ipcRenderer.invoke(IPC.listConversations, noteId),
  createConversation: (req) => ipcRenderer.invoke(IPC.createConversation, req),
  getConversation: (id) => ipcRenderer.invoke(IPC.getConversation, id),
  deleteConversation: (id) => ipcRenderer.invoke(IPC.deleteConversation, id),
  listMessages: (conversationId) => ipcRenderer.invoke(IPC.listMessages, conversationId),
  sendMessage: (conversationId, req) => ipcRenderer.invoke(IPC.sendMessage, conversationId, req),
  getCalendarEvents: (from: string, to: string) => ipcRenderer.invoke(IPC.getCalendarEvents, from, to),
  getGoogleCalendarOAuthStatus: () => ipcRenderer.invoke(IPC.getGoogleCalendarOAuthStatus),
  openGoogleCalendarOAuthStart: () => ipcRenderer.invoke(IPC.openGoogleCalendarOAuthStart),
  getMicrosoftCalendarOAuthStatus: () => ipcRenderer.invoke(IPC.getMicrosoftCalendarOAuthStatus),
  openMicrosoftCalendarOAuthStart: () => ipcRenderer.invoke(IPC.openMicrosoftCalendarOAuthStart),
  onUploadProgress: (cb: (p: UploadProgress) => void) => {
    const listener = (_e: unknown, p: UploadProgress) => cb(p)
    ipcRenderer.on(IPC.uploadProgress, listener)
    return () => ipcRenderer.removeListener(IPC.uploadProgress, listener)
  },
  onNoteStreamEvent: (cb) => {
    const listener = (_e: unknown, event: Parameters<typeof cb>[0]) => cb(event)
    ipcRenderer.on(IPC.noteStreamEvent, listener)
    return () => ipcRenderer.removeListener(IPC.noteStreamEvent, listener)
  },
}

contextBridge.exposeInMainWorld('muesli', bridge)
